#pragma once


// MISCELLANEOUS DEFINITIONS
#define SERIAL_SPEED 115200

// LED DEFINITIONS
#define LED_PIN 2
#define NUM_LEDS 64
#define LED_TYPE WS2812B
#define LED_COLOR_ORDER GRB

// BUTTON DEFINITIONS
#define BUTTON_PIN 14
#define BUTTON_DEBOUNCE 50
#define BUTTON_LONG_PRESS_THRESHOLD 300

// WIFI DEFINITIONS
#define WIFI_SSID "Network Not Found"
// #define WIFI_SSID "rMatrix WiFi"